#!/usr/bin/env python3

from scipy.stats import poisson
from scipy.stats import uniform

print ("ifo, start, stop, range") 

for ifo, mean in (("H1", 150), ("L1", 160), ("V1", 50), ("K1", 10)):
    cnt = 0
    start = nxt = prev = 1434000000
    end = 1435000000
    while nxt < end:
        cnt += 1
        nxt += poisson.rvs(10) * 100
        if cnt % 2:
            rng = 0
        else:
            rng = uniform.rvs(loc=mean/2, scale=mean/2 + mean/10)
        print (", ".join((ifo, str(prev), str(nxt), str(rng))))
        prev=nxt
