# Generated by Django 4.2.10 on 2025-06-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectorRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ifo", models.CharField(db_index=True, max_length=10)),
                ("start", models.BigIntegerField(db_index=True)),
                ("stop", models.BigIntegerField(db_index=True)),
                ("range", models.FloatField()),
            ],
            options={
                "ordering": ["ifo", "start"],
                "indexes": [
                    models.Index(
                        fields=["ifo", "start", "stop"],
                        name="detector_ra_ifo_4dee6a_idx",
                    )
                ],
            },
        ),
    ]
